site_name: DynamicGui Documentation
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
nav:
  - Basics: index.md
  - GUI Anatomy: anatomy/index.md
  - Functions:
    - Introduction: functions/index.md
    - Anatomy: functions/anatomy.md
    - List of Functions: functions/function-list.md
  - Macros: macros/index.md
  - Wiki Updates: updates/index.md